### ISSUE TITLE
Wirecloud failed to run in Firefox / Chrome

### ISSUE THREAD

**Issue by arilwan** [Wirecloud/docker-wirecloud#26]
Dear Commnity,
I am running dockerized images of wirecloud+nginx from a remote server, trying to access Wirecloud from my browser. Wirecloud failed to load correctly, issuing the following message:
```
Your browser seems to lack some required features
We recommend you to upgrade your browser to the newest version of either Firefox or Google Chrome as these are the browsers currently supported by WireCloud.
```
![new wirecloud](https://user-images.githubusercontent.com/42409395/54522125-5e59a000-4964-11e9-83e3-e56809e49850.png)

I can confirm my browsers (firefox and chrome) are up-to-date, and I can run wirecloud locally on my machine using same browsers, as in following image:
![wirecloud 2](https://user-images.githubusercontent.com/42409395/54319825-ca45ac80-45e2-11e9-97e5-35fab8011d75.png)

Any idea why this problem happpens? Below is my `docker-compose` file.
```
version: "3.1"
services:
 nginx:
    restart: always
    container_name: fiware-nginx
    image: nginx
    networks:
      - default
    ports:
      - 53153:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wirecloud-static:/var/www/static:ro
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - wirecloud
 postgres:
    restart: always
    image: postgres:10
    hostname: postgres
    container_name: fiware-postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 elasticsearch:
    restart: always
    container_name: fiware-elasticsearch
    image: elasticsearch:2.4
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    command: elasticsearch  -Des.index.max_result_window=50000
 memcached:
    restart: always
    container_name: fiware-memcached
    image: memcached:1
    command: memcached -m 2048m  
 wirecloud:
    restart: always
    image: fiware/wirecloud
    container_name: fiware-wirecloud
    networks:
        - default
    depends_on:
        - postgres
        - elasticsearch
        - memcached
    environment:
        - DEBUG=False
        - DB_HOST=postgres
        - DB_PASSWORD=password # Change this password!
        - FORWARDED_ALLOW_IPS=*
        - ELASTICSEARCH2_URL=http://elasticsearch:9200/
        - MEMCACHED_LOCATION=memcached:11211
    volumes:
      - ./wirecloud-data:/opt/wirecloud_instance/data
      - ./static:/var/www/static

```

**Comment by arilwan** [comment]
Hi @aarranz 
Can you spot what is causing this problem, please? Can't figure out what's the cause.

**Comment by arilwan** [comment]
I tried this with Safari too, same problem.

**Comment by aarranz** [comment]
Hi @arilwan,

Sorry for the delay, It seems a problem with the static files. Please, try following those steps:

- Update nginx configuration to make it listen directly on port 53153.
   ```
       server {
   
           listen 80;
   ```
   Should be changed to:
   ```
       server {
   
           listen 53153;
   ```
- Update `docker-compose.yml` by replacing nginx port mapping from this:
  ```
       ports:
         - 53153:80
   ```
   to this:
  ```
       ports:
         - 53153:53153
   ```

Best Regards,
Álvaro

**Comment by arilwan** [comment]
Hi @aarranz 

Just made these changes and restarts services, yet I'm receiving same message as before.

**Comment by arilwan** [comment]
Changing to another open port doesn't solve the problem...

**Comment by arilwan** [comment]
Hi @aarranz 
I share here my `nginx.conf` file:
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
   #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {

        listen 53153;

        #server_name example.org MY_SERVER_IP;

        client_max_body_size 20M;
        charset utf-8;

        location /static {
            alias /var/www/static;
        }

        location / {
            proxy_pass http://wirecloud:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
       location /iotagent {
           proxy_pass http://fiware-iotagent:4041;

        }

    }
}

```
port mapping in `docker-compose.yml`:
```
ports:
       - "53153:53153"
```

**Comment by aarranz** [comment]
I found the problems, you have changed folder name for static files on the wirecloud service (to `static`), but you are using the old name (`wirecloud-static`) on the nginx service. This make nginx not able to serve static files. On the other hand, as you are using a custom port, you have to indicate it by changing the following line:

    proxy_set_header Host $host;

to

    proxy_set_header Host $host:53153;

on the `nginx.conf` file.

Hope this solve your problems.

**Comment by arilwan** [comment]
Great! It works... closing.

**Comment by jeremymeyers** [comment]
This seems to still be a problem with the https://hub.docker.com/r/fiware/wirecloud image, if one wants to have wirecloud live on a port other than 8000 (which in my case is already taken).

<img width="1433" alt="Screen Shot 2021-12-09 at 5 22 36 PM" src="https://user-images.githubusercontent.com/3514095/145485115-7e27b5ad-f967-4aad-b3d6-b9c09a2f4bf3.png">

<img width="1180" alt="Screen Shot 2021-12-09 at 5 23 24 PM" src="https://user-images.githubusercontent.com/3514095/145485190-c1a4acbf-0fc0-4196-81ee-d523e8ae9343.png">
