### ISSUE TITLE
Unable to launch docker image of wirecloud

### ISSUE THREAD

**Issue by tukiyo** [Wirecloud/docker-wirecloud#64]
## ■ I got an error when I put `-e DEBUG=False` or unspecified.

```sh
docker run -p 8000:8000 \
 -e DEBUG=False \
 fiware/wirecloud:1.2
```

or 

```sh
docker run -p 8000:8000 \
 fiware/wirecloud:1.2
```

* http://localhost:8000

![image](https://user-images.githubusercontent.com/1517645/122641182-98ffa380-d13e-11eb-8b3f-e2ea9e37ef1c.png)

## ■ No error with `-e DEBUG=True`

```sh
docker run -p 8000:8000 \
 -e DEBUG=True \
 fiware/wirecloud:1.2
```

![image](https://user-images.githubusercontent.com/1517645/122641025-9c465f80-d13d-11eb-8fba-c4c29e4431ae.png)

I had the same problem with `fiware/wirecloud:1.3` and  `fiware/wirecloud:latest`.

Why do I need to add `-e DEBUG=True`?

**Comment by fisuda** [comment]
When `DEBUG` is False, you should serve the static files with a fast performance http server like Apache, Nginx, Gunicorn, etc.
Please see [Django configuration](https://github.com/Wirecloud/wirecloud/blob/develop/docs/installation_guide.md#django-configuration) in WireCloud documentation.

**Comment by tukiyo** [comment]
単体起動だとそうだったのですね、ありがとうございました。
