### ISSUE TITLE
Wirecloud docker container exits just after restarting it

### ISSUE THREAD

**Issue by sdhouib** [Wirecloud/docker-wirecloud#8]
After installing wirecloud through this command :

$ docker run --name some-wirecloud -d -p 80:80 fiware/wirecloud:latest

Wirecloud is running without any problem. But when I reboot my computer 
and restart the docker container of wirecloud through this command: 
$ docker restart some-wirecloud 
the docker container exits just after restarting :

$ docker container ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                              PORTS                    NAMES
9c5ade363d3f        fiware/ngsiproxy          "/bin/sh -c ngsi-p..."   3 days ago          Up 2 days                           3000/tcp                 beincpps-ngsiproxy
61c5dedd1bc7        fiware/wirecloud:latest   "/docker-entrypoin..."   3 days ago          Exited (0) Less than a second ago                            some-wirecloud

What is the best way to manage restarting the docker container after rebooting the machine ?

**Comment by sdhouib** [comment]
figured out what was wrong the wirecloud container. The issue was that the apache server could not restart since it was keepin in memory the pid of the last running process.
So I modified the docker entrypoint file to add this line: rm -f /var/run/apache2/apache2.pid as shown below:

# Start apache processes in foreground
/usr/sbin/apache2ctl graceful-stop
**rm -f /var/run/apache2/apache2.pid**
exec /usr/sbin/apache2ctl -D FOREGROUND

Could you please modify the docker-entrypoint.sh accordingly ?
Thanks

**Comment by aarranz** [comment]
Hi @sdhouib, thank you very much, I'm integrating your changes.

**Comment by aarranz** [comment]
Changes merged. New version of the images are in their way (see the [build queue](https://hub.docker.com/r/fiware/wirecloud/builds/) for more details).

**Comment by sdhouib** [comment]
Thanks!
